# Generated by Django 2.2 on 2020-05-24 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6)])),
                ('verification', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=11)),
                ('shopname', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('credit', models.SmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6)])),
                ('telephone', models.CharField(max_length=11)),
                ('verification', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('introduction', models.TextField(null=True)),
            ],
        ),
    ]
