# Generated by Django 3.0.4 on 2020-05-25 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='shopname',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
